// Granular Step Flow Definitions
// Ultra-detailed step-by-step flows for each booking type

import { StepMetadata, FlightBookingStep, RideBookingStep, DoctorBookingStep } from '../types';
import { Colors } from './theme';

// ============================================
// FLIGHT BOOKING STEPS
// ============================================

export const FLIGHT_PLANNING_STEPS: StepMetadata[] = [
  {
    id: 'connect_api',
    step: 'connect_api' as FlightBookingStep,
    phase: 'understand',
    label: 'Connecting',
    description: 'Establishing secure connection to flight APIs...',
    status: 'pending',
    icon: 'radio-outline',
    color: '#6366F1',
    accentColor: '#818CF8',
  },
  {
    id: 'authenticate_user',
    step: 'authenticate_user' as FlightBookingStep,
    phase: 'understand',
    label: 'Authenticating',
    description: 'Verifying your identity and preferences...',
    status: 'pending',
    icon: 'shield-checkmark-outline',
    color: '#8B5CF6',
    accentColor: '#A78BFA',
  },
  {
    id: 'detect_location',
    step: 'detect_location' as FlightBookingStep,
    phase: 'understand',
    label: 'Locating',
    description: 'Detecting your current location via GPS...',
    status: 'pending',
    icon: 'location-outline',
    color: '#EC4899',
    accentColor: '#F472B6',
  },
  {
    id: 'parse_intent',
    step: 'parse_intent' as FlightBookingStep,
    phase: 'understand',
    label: 'Understanding',
    description: 'Analyzing your travel request with AI...',
    status: 'pending',
    icon: 'bulb-outline',
    color: '#F59E0B',
    accentColor: '#FBBF24',
  },
  {
    id: 'extract_origin',
    step: 'extract_origin' as FlightBookingStep,
    phase: 'understand',
    label: 'Origin Detection',
    description: 'Identifying departure city and airport...',
    status: 'pending',
    icon: 'navigate-outline',
    color: '#10B981',
    accentColor: '#34D399',
  },
  {
    id: 'extract_destination',
    step: 'extract_destination' as FlightBookingStep,
    phase: 'understand',
    label: 'Destination Detection',
    description: 'Identifying arrival city and airport...',
    status: 'pending',
    icon: 'flag-outline',
    color: '#06B6D4',
    accentColor: '#22D3EE',
  },
  {
    id: 'validate_dates',
    step: 'validate_dates' as FlightBookingStep,
    phase: 'understand',
    label: 'Date Validation',
    description: 'Calculating and validating travel dates...',
    status: 'pending',
    icon: 'calendar-outline',
    color: '#3B82F6',
    accentColor: '#60A5FA',
  },
  {
    id: 'analyze_budget',
    step: 'analyze_budget' as FlightBookingStep,
    phase: 'understand',
    label: 'Budget Analysis',
    description: 'Analyzing your budget constraints...',
    status: 'pending',
    icon: 'wallet-outline',
    color: '#F59E0B',
    accentColor: '#FBBF24',
  },
  {
    id: 'determine_cabin_class',
    step: 'determine_cabin_class' as FlightBookingStep,
    phase: 'understand',
    label: 'Cabin Class',
    description: 'Determining preferred cabin class...',
    status: 'pending',
    icon: 'ribbon-outline',
    color: '#8B5CF6',
    accentColor: '#A78BFA',
  },
  {
    id: 'check_traveler_count',
    step: 'check_traveler_count' as FlightBookingStep,
    phase: 'understand',
    label: 'Travelers',
    description: 'Confirming number of passengers...',
    status: 'pending',
    icon: 'people-outline',
    color: '#EC4899',
    accentColor: '#F472B6',
  },
];

export const FLIGHT_SEARCH_STEPS: StepMetadata[] = [
  {
    id: 'query_flight_api',
    step: 'query_flight_api' as FlightBookingStep,
    phase: 'search',
    label: 'Querying Airlines',
    description: 'Contacting 500+ airlines worldwide...',
    status: 'pending',
    icon: 'airplane-outline',
    color: '#3B82F6',
    accentColor: '#60A5FA',
  },
  {
    id: 'fetch_airline_data',
    step: 'fetch_airline_data' as FlightBookingStep,
    phase: 'search',
    label: 'Fetching Data',
    description: 'Retrieving real-time flight information...',
    status: 'pending',
    icon: 'cloud-download-outline',
    color: '#06B6D4',
    accentColor: '#22D3EE',
  },
  {
    id: 'filter_results',
    step: 'filter_results' as FlightBookingStep,
    phase: 'search',
    label: 'Filtering',
    description: 'Applying filters and constraints...',
    status: 'pending',
    icon: 'funnel-outline',
    color: '#8B5CF6',
    accentColor: '#A78BFA',
  },
  {
    id: 'apply_preferences',
    step: 'apply_preferences' as FlightBookingStep,
    phase: 'search',
    label: 'Preferences',
    description: 'Applying your travel preferences...',
    status: 'pending',
    icon: 'options-outline',
    color: '#10B981',
    accentColor: '#34D399',
  },
  {
    id: 'calculate_duration',
    step: 'calculate_duration' as FlightBookingStep,
    phase: 'search',
    label: 'Duration',
    description: 'Calculating flight durations and layovers...',
    status: 'pending',
    icon: 'time-outline',
    color: '#F59E0B',
    accentColor: '#FBBF24',
  },
];

export const FLIGHT_COMPARE_STEPS: StepMetadata[] = [
  {
    id: 'compare_prices',
    step: 'compare_prices' as FlightBookingStep,
    phase: 'compare',
    label: 'Price Comparison',
    description: 'Analyzing fares across all options...',
    status: 'pending',
    icon: 'stats-chart-outline',
    color: '#8B5CF6',
    accentColor: '#A78BFA',
  },
  {
    id: 'rank_by_value',
    step: 'rank_by_value' as FlightBookingStep,
    phase: 'compare',
    label: 'Ranking',
    description: 'Ranking flights by best value...',
    status: 'pending',
    icon: 'trophy-outline',
    color: '#F59E0B',
    accentColor: '#FBBF24',
  },
  {
    id: 'check_availability',
    step: 'check_availability' as FlightBookingStep,
    phase: 'compare',
    label: 'Availability',
    description: 'Verifying seat availability...',
    status: 'pending',
    icon: 'checkmark-circle-outline',
    color: '#10B981',
    accentColor: '#34D399',
  },
  {
    id: 'verify_seats',
    step: 'verify_seats' as FlightBookingStep,
    phase: 'compare',
    label: 'Seat Verification',
    description: 'Checking seat configurations...',
    status: 'pending',
    icon: 'grid-outline',
    color: '#06B6D4',
    accentColor: '#22D3EE',
  },
];

export const FLIGHT_BOOKING_STEPS: StepMetadata[] = [
  {
    id: 'select_best_option',
    step: 'select_best_option' as FlightBookingStep,
    phase: 'book',
    label: 'Selection',
    description: 'Selecting your preferred flight...',
    status: 'pending',
    icon: 'checkmark-done-outline',
    color: '#10B981',
    accentColor: '#34D399',
  },
  {
    id: 'hold_reservation',
    step: 'hold_reservation' as FlightBookingStep,
    phase: 'hold',
    label: 'Holding',
    description: 'Placing temporary hold on seats...',
    status: 'pending',
    icon: 'lock-closed-outline',
    color: '#F59E0B',
    accentColor: '#FBBF24',
  },
  {
    id: 'check_tsa_precheck',
    step: 'check_tsa_precheck' as FlightBookingStep,
    phase: 'book',
    label: 'TSA PreCheck',
    description: 'Verifying TSA PreCheck eligibility...',
    status: 'pending',
    icon: 'shield-checkmark-outline',
    color: '#3B82F6',
    accentColor: '#60A5FA',
  },
  {
    id: 'verify_travel_documents',
    step: 'verify_travel_documents' as FlightBookingStep,
    phase: 'book',
    label: 'Travel Documents',
    description: 'Checking visa and travel requirements...',
    status: 'pending',
    icon: 'document-text-outline',
    color: '#8B5CF6',
    accentColor: '#A78BFA',
  },
  {
    id: 'assign_seats',
    step: 'assign_seats' as FlightBookingStep,
    phase: 'book',
    label: 'Seat Assignment',
    description: 'Selecting your preferred seats...',
    status: 'pending',
    icon: 'grid-outline',
    color: '#EC4899',
    accentColor: '#F472B6',
  },
  {
    id: 'select_baggage',
    step: 'select_baggage' as FlightBookingStep,
    phase: 'book',
    label: 'Baggage Selection',
    description: 'Configuring baggage allowance...',
    status: 'pending',
    icon: 'briefcase-outline',
    color: '#F59E0B',
    accentColor: '#FBBF24',
  },
  {
    id: 'add_meal_preferences',
    step: 'add_meal_preferences' as FlightBookingStep,
    phase: 'book',
    label: 'Meal Preferences',
    description: 'Selecting in-flight meals...',
    status: 'pending',
    icon: 'restaurant-outline',
    color: '#10B981',
    accentColor: '#34D399',
  },
  {
    id: 'add_special_assistance',
    step: 'add_special_assistance' as FlightBookingStep,
    phase: 'book',
    label: 'Special Assistance',
    description: 'Configuring accessibility needs...',
    status: 'pending',
    icon: 'accessibility-outline',
    color: '#06B6D4',
    accentColor: '#22D3EE',
  },
  {
    id: 'check_frequent_flyer',
    step: 'check_frequent_flyer' as FlightBookingStep,
    phase: 'book',
    label: 'Frequent Flyer',
    description: 'Adding loyalty program details...',
    status: 'pending',
    icon: 'star-outline',
    color: '#F59E0B',
    accentColor: '#FBBF24',
  },
  {
    id: 'offer_travel_insurance',
    step: 'offer_travel_insurance' as FlightBookingStep,
    phase: 'book',
    label: 'Travel Insurance',
    description: 'Reviewing insurance options...',
    status: 'pending',
    icon: 'shield-outline',
    color: '#8B5CF6',
    accentColor: '#A78BFA',
  },
  {
    id: 'verify_passenger_info',
    step: 'verify_passenger_info' as FlightBookingStep,
    phase: 'book',
    label: 'Passenger Info',
    description: 'Verifying traveler information...',
    status: 'pending',
    icon: 'person-outline',
    color: '#6366F1',
    accentColor: '#818CF8',
  },
  {
    id: 'validate_passport',
    step: 'validate_passport' as FlightBookingStep,
    phase: 'book',
    label: 'Passport Check',
    description: 'Validating passport details...',
    status: 'pending',
    icon: 'document-text-outline',
    color: '#8B5CF6',
    accentColor: '#A78BFA',
  },
  {
    id: 'process_payment',
    step: 'process_payment' as FlightBookingStep,
    phase: 'pay',
    label: 'Payment',
    description: 'Processing secure payment...',
    status: 'pending',
    icon: 'card-outline',
    color: '#059669',
    accentColor: '#10B981',
  },
  {
    id: 'confirm_booking',
    step: 'confirm_booking' as FlightBookingStep,
    phase: 'confirm',
    label: 'Confirmation',
    description: 'Confirming your booking...',
    status: 'pending',
    icon: 'checkmark-done-outline',
    color: '#10B981',
    accentColor: '#34D399',
  },
  {
    id: 'generate_pnr',
    step: 'generate_pnr' as FlightBookingStep,
    phase: 'confirm',
    label: 'PNR Generation',
    description: 'Generating booking reference...',
    status: 'pending',
    icon: 'barcode-outline',
    color: '#3B82F6',
    accentColor: '#60A5FA',
  },
  {
    id: 'generate_eticket',
    step: 'generate_eticket' as FlightBookingStep,
    phase: 'confirm',
    label: 'E-Ticket',
    description: 'Generating electronic ticket...',
    status: 'pending',
    icon: 'ticket-outline',
    color: '#EC4899',
    accentColor: '#F472B6',
  },
  {
    id: 'send_confirmation_email',
    step: 'send_confirmation_email' as FlightBookingStep,
    phase: 'confirm',
    label: 'Email',
    description: 'Sending confirmation email...',
    status: 'pending',
    icon: 'mail-outline',
    color: '#06B6D4',
    accentColor: '#22D3EE',
  },
  {
    id: 'setup_mobile_boarding_pass',
    step: 'setup_mobile_boarding_pass' as FlightBookingStep,
    phase: 'confirm',
    label: 'Mobile Pass',
    description: 'Setting up mobile boarding pass...',
    status: 'pending',
    icon: 'phone-portrait-outline',
    color: '#3B82F6',
    accentColor: '#60A5FA',
  },
  {
    id: 'create_calendar_event',
    step: 'create_calendar_event' as FlightBookingStep,
    phase: 'calendar',
    label: 'Calendar',
    description: 'Adding to your calendar...',
    status: 'pending',
    icon: 'calendar-number-outline',
    color: '#3B82F6',
    accentColor: '#60A5FA',
  },
  {
    id: 'set_checkin_reminder',
    step: 'set_checkin_reminder' as FlightBookingStep,
    phase: 'calendar',
    label: 'Check-in Reminder',
    description: 'Setting 24h check-in reminder...',
    status: 'pending',
    icon: 'alarm-outline',
    color: '#F59E0B',
    accentColor: '#FBBF24',
  },
  {
    id: 'set_departure_reminder',
    step: 'set_departure_reminder' as FlightBookingStep,
    phase: 'calendar',
    label: 'Departure Reminder',
    description: 'Setting departure reminders...',
    status: 'pending',
    icon: 'notifications-outline',
    color: '#8B5CF6',
    accentColor: '#A78BFA',
  },
  {
    id: 'enable_flight_monitoring',
    step: 'enable_flight_monitoring' as FlightBookingStep,
    phase: 'monitor',
    label: 'Flight Monitoring',
    description: 'Enabling real-time flight tracking...',
    status: 'pending',
    icon: 'eye-outline',
    color: '#10B981',
    accentColor: '#34D399',
  },
  {
    id: 'enable_delay_alerts',
    step: 'enable_delay_alerts' as FlightBookingStep,
    phase: 'monitor',
    label: 'Delay Alerts',
    description: 'Setting up delay notifications...',
    status: 'pending',
    icon: 'alert-circle-outline',
    color: '#EF4444',
    accentColor: '#F87171',
  },
  {
    id: 'enable_gate_notifications',
    step: 'enable_gate_notifications' as FlightBookingStep,
    phase: 'monitor',
    label: 'Gate Updates',
    description: 'Enabling gate change alerts...',
    status: 'pending',
    icon: 'navigate-outline',
    color: '#06B6D4',
    accentColor: '#22D3EE',
  },
  {
    id: 'setup_weather_alerts',
    step: 'setup_weather_alerts' as FlightBookingStep,
    phase: 'monitor',
    label: 'Weather Alerts',
    description: 'Configuring weather notifications...',
    status: 'pending',
    icon: 'cloud-outline',
    color: '#3B82F6',
    accentColor: '#60A5FA',
  },
];

// ============================================
// RIDE BOOKING STEPS
// ============================================

export const RIDE_PLANNING_STEPS: StepMetadata[] = [
  {
    id: 'detect_current_location',
    step: 'detect_current_location' as RideBookingStep,
    phase: 'understand',
    label: 'Location Detection',
    description: 'Pinpointing your exact GPS location...',
    status: 'pending',
    icon: 'location-outline',
    color: '#3B82F6',
    accentColor: '#60A5FA',
  },
  {
    id: 'parse_destination',
    step: 'parse_destination' as RideBookingStep,
    phase: 'understand',
    label: 'Destination',
    description: 'Understanding your destination...',
    status: 'pending',
    icon: 'flag-outline',
    color: '#10B981',
    accentColor: '#34D399',
  },
  {
    id: 'validate_addresses',
    step: 'validate_addresses' as RideBookingStep,
    phase: 'understand',
    label: 'Address Validation',
    description: 'Validating pickup and dropoff addresses...',
    status: 'pending',
    icon: 'checkmark-circle-outline',
    color: '#8B5CF6',
    accentColor: '#A78BFA',
  },
  {
    id: 'connect_uber_api',
    step: 'connect_uber_api' as RideBookingStep,
    phase: 'search',
    label: 'Uber Connection',
    description: 'Connecting to Uber API...',
    status: 'pending',
    icon: 'car-sport-outline',
    color: '#000000',
    accentColor: '#333333',
  },
  {
    id: 'connect_lyft_api',
    step: 'connect_lyft_api' as RideBookingStep,
    phase: 'search',
    label: 'Lyft Connection',
    description: 'Connecting to Lyft API...',
    status: 'pending',
    icon: 'car-outline',
    color: '#FF00BF',
    accentColor: '#FF66D9',
  },
];

export const RIDE_SEARCH_STEPS: StepMetadata[] = [
  {
    id: 'search_nearby_drivers',
    step: 'search_nearby_drivers' as RideBookingStep,
    phase: 'search',
    label: 'Finding Drivers',
    description: 'Searching for available drivers nearby...',
    status: 'pending',
    icon: 'search-outline',
    color: '#8B5CF6',
    accentColor: '#A78BFA',
  },
  {
    id: 'calculate_route',
    step: 'calculate_route' as RideBookingStep,
    phase: 'search',
    label: 'Route Calculation',
    description: 'Optimizing your journey route...',
    status: 'pending',
    icon: 'git-branch-outline',
    color: '#10B981',
    accentColor: '#34D399',
  },
  {
    id: 'estimate_duration',
    step: 'estimate_duration' as RideBookingStep,
    phase: 'search',
    label: 'Duration',
    description: 'Estimating trip duration...',
    status: 'pending',
    icon: 'time-outline',
    color: '#F59E0B',
    accentColor: '#FBBF24',
  },
  {
    id: 'get_price_estimates',
    step: 'get_price_estimates' as RideBookingStep,
    phase: 'compare',
    label: 'Price Estimates',
    description: 'Getting price estimates from providers...',
    status: 'pending',
    icon: 'pricetag-outline',
    color: '#F59E0B',
    accentColor: '#FBBF24',
  },
  {
    id: 'compare_providers',
    step: 'compare_providers' as RideBookingStep,
    phase: 'compare',
    label: 'Comparing',
    description: 'Comparing ride options and prices...',
    status: 'pending',
    icon: 'git-compare-outline',
    color: '#8B5CF6',
    accentColor: '#A78BFA',
  },
  {
    id: 'select_vehicle_type',
    step: 'select_vehicle_type' as RideBookingStep,
    phase: 'compare',
    label: 'Vehicle Type',
    description: 'Selecting best vehicle type...',
    status: 'pending',
    icon: 'car-outline',
    color: '#06B6D4',
    accentColor: '#22D3EE',
  },
];

export const RIDE_BOOKING_STEPS: StepMetadata[] = [
  {
    id: 'check_accessibility_needs',
    step: 'check_accessibility_needs' as RideBookingStep,
    phase: 'book',
    label: 'Accessibility',
    description: 'Checking accessibility requirements...',
    status: 'pending',
    icon: 'accessibility-outline',
    color: '#8B5CF6',
    accentColor: '#A78BFA',
  },
  {
    id: 'check_child_seat',
    step: 'check_child_seat' as RideBookingStep,
    phase: 'book',
    label: 'Child Seat',
    description: 'Verifying child seat availability...',
    status: 'pending',
    icon: 'person-outline',
    color: '#EC4899',
    accentColor: '#F472B6',
  },
  {
    id: 'check_pet_friendly',
    step: 'check_pet_friendly' as RideBookingStep,
    phase: 'book',
    label: 'Pet-Friendly',
    description: 'Finding pet-friendly vehicles...',
    status: 'pending',
    icon: 'paw-outline',
    color: '#F59E0B',
    accentColor: '#FBBF24',
  },
  {
    id: 'verify_luggage_capacity',
    step: 'verify_luggage_capacity' as RideBookingStep,
    phase: 'book',
    label: 'Luggage Check',
    description: 'Verifying luggage capacity...',
    status: 'pending',
    icon: 'briefcase-outline',
    color: '#06B6D4',
    accentColor: '#22D3EE',
  },
  {
    id: 'check_driver_availability',
    step: 'check_driver_availability' as RideBookingStep,
    phase: 'book',
    label: 'Driver Check',
    description: 'Verifying driver availability...',
    status: 'pending',
    icon: 'person-circle-outline',
    color: '#3B82F6',
    accentColor: '#60A5FA',
  },
  {
    id: 'request_ride',
    step: 'request_ride' as RideBookingStep,
    phase: 'book',
    label: 'Requesting',
    description: 'Sending ride request...',
    status: 'pending',
    icon: 'send-outline',
    color: '#EC4899',
    accentColor: '#F472B6',
  },
  {
    id: 'match_driver',
    step: 'match_driver' as RideBookingStep,
    phase: 'book',
    label: 'Matching',
    description: 'Matching you with a driver...',
    status: 'pending',
    icon: 'people-outline',
    color: '#10B981',
    accentColor: '#34D399',
  },
  {
    id: 'verify_driver_background',
    step: 'verify_driver_background' as RideBookingStep,
    phase: 'book',
    label: 'Background Check',
    description: 'Verifying driver credentials...',
    status: 'pending',
    icon: 'shield-checkmark-outline',
    color: '#10B981',
    accentColor: '#34D399',
  },
  {
    id: 'show_vehicle_details',
    step: 'show_vehicle_details' as RideBookingStep,
    phase: 'book',
    label: 'Vehicle Info',
    description: 'Loading vehicle details...',
    status: 'pending',
    icon: 'car-outline',
    color: '#3B82F6',
    accentColor: '#60A5FA',
  },
  {
    id: 'calculate_fare_breakdown',
    step: 'calculate_fare_breakdown' as RideBookingStep,
    phase: 'book',
    label: 'Fare Breakdown',
    description: 'Calculating detailed fare...',
    status: 'pending',
    icon: 'calculator-outline',
    color: '#F59E0B',
    accentColor: '#FBBF24',
  },
  {
    id: 'confirm_pickup',
    step: 'confirm_pickup' as RideBookingStep,
    phase: 'confirm',
    label: 'Confirmation',
    description: 'Confirming pickup details...',
    status: 'pending',
    icon: 'checkmark-done-outline',
    color: '#22C55E',
    accentColor: '#4ADE80',
  },
  {
    id: 'track_driver_location',
    step: 'track_driver_location' as RideBookingStep,
    phase: 'monitor',
    label: 'Tracking',
    description: 'Tracking driver location...',
    status: 'pending',
    icon: 'navigate-outline',
    color: '#3B82F6',
    accentColor: '#60A5FA',
  },
  {
    id: 'update_eta',
    step: 'update_eta' as RideBookingStep,
    phase: 'monitor',
    label: 'ETA Update',
    description: 'Updating arrival time...',
    status: 'pending',
    icon: 'time-outline',
    color: '#06B6D4',
    accentColor: '#22D3EE',
  },
  {
    id: 'optimize_route',
    step: 'optimize_route' as RideBookingStep,
    phase: 'monitor',
    label: 'Route Optimization',
    description: 'Optimizing route in real-time...',
    status: 'pending',
    icon: 'git-branch-outline',
    color: '#10B981',
    accentColor: '#34D399',
  },
  {
    id: 'process_payment',
    step: 'process_payment' as RideBookingStep,
    phase: 'pay',
    label: 'Payment',
    description: 'Processing payment...',
    status: 'pending',
    icon: 'card-outline',
    color: '#059669',
    accentColor: '#10B981',
  },
  {
    id: 'calculate_tip',
    step: 'calculate_tip' as RideBookingStep,
    phase: 'pay',
    label: 'Tip Calculation',
    description: 'Calculating suggested tip...',
    status: 'pending',
    icon: 'cash-outline',
    color: '#F59E0B',
    accentColor: '#FBBF24',
  },
  {
    id: 'generate_receipt',
    step: 'generate_receipt' as RideBookingStep,
    phase: 'confirm',
    label: 'Receipt',
    description: 'Generating ride receipt...',
    status: 'pending',
    icon: 'receipt-outline',
    color: '#8B5CF6',
    accentColor: '#A78BFA',
  },
  {
    id: 'send_ride_details',
    step: 'send_ride_details' as RideBookingStep,
    phase: 'confirm',
    label: 'Details',
    description: 'Sending ride details...',
    status: 'pending',
    icon: 'mail-outline',
    color: '#06B6D4',
    accentColor: '#22D3EE',
  },
  {
    id: 'request_rating',
    step: 'request_rating' as RideBookingStep,
    phase: 'confirm',
    label: 'Rating',
    description: 'Requesting ride rating...',
    status: 'pending',
    icon: 'star-outline',
    color: '#F59E0B',
    accentColor: '#FBBF24',
  },
];

// ============================================
// DOCTOR APPOINTMENT STEPS
// ============================================

export const DOCTOR_PLANNING_STEPS: StepMetadata[] = [
  {
    id: 'parse_symptoms',
    step: 'parse_symptoms' as DoctorBookingStep,
    phase: 'understand',
    label: 'Symptoms Analysis',
    description: 'Analyzing your health concerns...',
    status: 'pending',
    icon: 'medkit-outline',
    color: '#EF4444',
    accentColor: '#F87171',
  },
  {
    id: 'identify_specialty',
    step: 'identify_specialty' as DoctorBookingStep,
    phase: 'understand',
    label: 'Specialty',
    description: 'Identifying required medical specialty...',
    status: 'pending',
    icon: 'medical-outline',
    color: '#3B82F6',
    accentColor: '#60A5FA',
  },
  {
    id: 'determine_urgency',
    step: 'determine_urgency' as DoctorBookingStep,
    phase: 'understand',
    label: 'Urgency',
    description: 'Determining appointment urgency...',
    status: 'pending',
    icon: 'alert-circle-outline',
    color: '#F59E0B',
    accentColor: '#FBBF24',
  },
  {
    id: 'detect_location',
    step: 'detect_location' as DoctorBookingStep,
    phase: 'understand',
    label: 'Location',
    description: 'Detecting your location...',
    status: 'pending',
    icon: 'location-outline',
    color: '#10B981',
    accentColor: '#34D399',
  },
  {
    id: 'set_search_radius',
    step: 'set_search_radius' as DoctorBookingStep,
    phase: 'understand',
    label: 'Search Radius',
    description: 'Setting search radius for providers...',
    status: 'pending',
    icon: 'radio-outline',
    color: '#06B6D4',
    accentColor: '#22D3EE',
  },
];

export const DOCTOR_SEARCH_STEPS: StepMetadata[] = [
  {
    id: 'verify_insurance',
    step: 'verify_insurance' as DoctorBookingStep,
    phase: 'search',
    label: 'Insurance',
    description: 'Verifying insurance information...',
    status: 'pending',
    icon: 'shield-checkmark-outline',
    color: '#10B981',
    accentColor: '#34D399',
  },
  {
    id: 'check_coverage',
    step: 'check_coverage' as DoctorBookingStep,
    phase: 'search',
    label: 'Coverage',
    description: 'Checking insurance coverage...',
    status: 'pending',
    icon: 'document-text-outline',
    color: '#8B5CF6',
    accentColor: '#A78BFA',
  },
  {
    id: 'search_providers',
    step: 'search_providers' as DoctorBookingStep,
    phase: 'search',
    label: 'Searching',
    description: 'Searching for qualified doctors...',
    status: 'pending',
    icon: 'search-outline',
    color: '#3B82F6',
    accentColor: '#60A5FA',
  },
  {
    id: 'filter_by_specialty',
    step: 'filter_by_specialty' as DoctorBookingStep,
    phase: 'search',
    label: 'Filtering',
    description: 'Filtering by specialty...',
    status: 'pending',
    icon: 'funnel-outline',
    color: '#EC4899',
    accentColor: '#F472B6',
  },
  {
    id: 'check_ratings',
    step: 'check_ratings' as DoctorBookingStep,
    phase: 'search',
    label: 'Ratings',
    description: 'Checking doctor ratings and reviews...',
    status: 'pending',
    icon: 'star-outline',
    color: '#F59E0B',
    accentColor: '#FBBF24',
  },
  {
    id: 'verify_credentials',
    step: 'verify_credentials' as DoctorBookingStep,
    phase: 'search',
    label: 'Credentials',
    description: 'Verifying medical credentials...',
    status: 'pending',
    icon: 'ribbon-outline',
    color: '#6366F1',
    accentColor: '#818CF8',
  },
];

export const DOCTOR_COMPARE_STEPS: StepMetadata[] = [
  {
    id: 'check_availability',
    step: 'check_availability' as DoctorBookingStep,
    phase: 'compare',
    label: 'Availability',
    description: 'Checking doctor availability...',
    status: 'pending',
    icon: 'calendar-outline',
    color: '#8B5CF6',
    accentColor: '#A78BFA',
  },
  {
    id: 'find_appointment_slots',
    step: 'find_appointment_slots' as DoctorBookingStep,
    phase: 'compare',
    label: 'Time Slots',
    description: 'Finding open appointment slots...',
    status: 'pending',
    icon: 'time-outline',
    color: '#3B82F6',
    accentColor: '#60A5FA',
  },
  {
    id: 'compare_doctors',
    step: 'compare_doctors' as DoctorBookingStep,
    phase: 'compare',
    label: 'Comparing',
    description: 'Comparing doctor options...',
    status: 'pending',
    icon: 'git-compare-outline',
    color: '#F59E0B',
    accentColor: '#FBBF24',
  },
  {
    id: 'rank_by_fit',
    step: 'rank_by_fit' as DoctorBookingStep,
    phase: 'compare',
    label: 'Ranking',
    description: 'Ranking doctors by best fit...',
    status: 'pending',
    icon: 'trophy-outline',
    color: '#10B981',
    accentColor: '#34D399',
  },
];

export const DOCTOR_BOOKING_STEPS: StepMetadata[] = [
  {
    id: 'select_doctor',
    step: 'select_doctor' as DoctorBookingStep,
    phase: 'book',
    label: 'Selection',
    description: 'Selecting the best doctor match...',
    status: 'pending',
    icon: 'person-outline',
    color: '#06B6D4',
    accentColor: '#22D3EE',
  },
  {
    id: 'review_medical_history',
    step: 'review_medical_history' as DoctorBookingStep,
    phase: 'book',
    label: 'Medical History',
    description: 'Reviewing your medical history...',
    status: 'pending',
    icon: 'document-text-outline',
    color: '#8B5CF6',
    accentColor: '#A78BFA',
  },
  {
    id: 'check_prescription_refills',
    step: 'check_prescription_refills' as DoctorBookingStep,
    phase: 'book',
    label: 'Prescriptions',
    description: 'Checking prescription refills...',
    status: 'pending',
    icon: 'medical-outline',
    color: '#10B981',
    accentColor: '#34D399',
  },
  {
    id: 'review_lab_results',
    step: 'review_lab_results' as DoctorBookingStep,
    phase: 'book',
    label: 'Lab Results',
    description: 'Reviewing recent lab results...',
    status: 'pending',
    icon: 'flask-outline',
    color: '#3B82F6',
    accentColor: '#60A5FA',
  },
  {
    id: 'verify_referral',
    step: 'verify_referral' as DoctorBookingStep,
    phase: 'book',
    label: 'Referral Check',
    description: 'Verifying referral requirements...',
    status: 'pending',
    icon: 'document-outline',
    color: '#F59E0B',
    accentColor: '#FBBF24',
  },
  {
    id: 'choose_appointment_type',
    step: 'choose_appointment_type' as DoctorBookingStep,
    phase: 'book',
    label: 'Appointment Type',
    description: 'Choosing in-person or telehealth...',
    status: 'pending',
    icon: 'videocam-outline',
    color: '#8B5CF6',
    accentColor: '#A78BFA',
  },
  {
    id: 'check_telehealth_equipment',
    step: 'check_telehealth_equipment' as DoctorBookingStep,
    phase: 'book',
    label: 'Equipment Check',
    description: 'Verifying telehealth setup...',
    status: 'pending',
    icon: 'desktop-outline',
    color: '#06B6D4',
    accentColor: '#22D3EE',
  },
  {
    id: 'select_time_slot',
    step: 'select_time_slot' as DoctorBookingStep,
    phase: 'book',
    label: 'Time Slot',
    description: 'Selecting appointment time...',
    status: 'pending',
    icon: 'calendar-number-outline',
    color: '#3B82F6',
    accentColor: '#60A5FA',
  },
  {
    id: 'verify_insurance_again',
    step: 'verify_insurance_again' as DoctorBookingStep,
    phase: 'book',
    label: 'Insurance Verify',
    description: 'Final insurance verification...',
    status: 'pending',
    icon: 'shield-checkmark-outline',
    color: '#10B981',
    accentColor: '#34D399',
  },
  {
    id: 'request_preauthorization',
    step: 'request_preauthorization' as DoctorBookingStep,
    phase: 'book',
    label: 'Pre-Authorization',
    description: 'Requesting insurance pre-auth...',
    status: 'pending',
    icon: 'shield-outline',
    color: '#8B5CF6',
    accentColor: '#A78BFA',
  },
  {
    id: 'book_appointment',
    step: 'book_appointment' as DoctorBookingStep,
    phase: 'confirm',
    label: 'Booking',
    description: 'Booking your appointment...',
    status: 'pending',
    icon: 'checkmark-done-outline',
    color: '#EC4899',
    accentColor: '#F472B6',
  },
  {
    id: 'send_confirmation',
    step: 'send_confirmation' as DoctorBookingStep,
    phase: 'confirm',
    label: 'Confirmation',
    description: 'Sending appointment confirmation...',
    status: 'pending',
    icon: 'mail-outline',
    color: '#22C55E',
    accentColor: '#4ADE80',
  },
  {
    id: 'send_pre_appointment_questionnaire',
    step: 'send_pre_appointment_questionnaire' as DoctorBookingStep,
    phase: 'confirm',
    label: 'Questionnaire',
    description: 'Sending pre-visit questionnaire...',
    status: 'pending',
    icon: 'clipboard-outline',
    color: '#3B82F6',
    accentColor: '#60A5FA',
  },
  {
    id: 'send_parking_directions',
    step: 'send_parking_directions' as DoctorBookingStep,
    phase: 'confirm',
    label: 'Directions',
    description: 'Sending parking and directions...',
    status: 'pending',
    icon: 'map-outline',
    color: '#10B981',
    accentColor: '#34D399',
  },
  {
    id: 'send_checkin_instructions',
    step: 'send_checkin_instructions' as DoctorBookingStep,
    phase: 'confirm',
    label: 'Check-in Info',
    description: 'Sending check-in instructions...',
    status: 'pending',
    icon: 'information-circle-outline',
    color: '#06B6D4',
    accentColor: '#22D3EE',
  },
  {
    id: 'create_calendar_event',
    step: 'create_calendar_event' as DoctorBookingStep,
    phase: 'calendar',
    label: 'Calendar',
    description: 'Adding to your calendar...',
    status: 'pending',
    icon: 'calendar-outline',
    color: '#3B82F6',
    accentColor: '#60A5FA',
  },
  {
    id: 'set_reminder_24h',
    step: 'set_reminder_24h' as DoctorBookingStep,
    phase: 'calendar',
    label: '24h Reminder',
    description: 'Setting 24-hour reminder...',
    status: 'pending',
    icon: 'alarm-outline',
    color: '#F59E0B',
    accentColor: '#FBBF24',
  },
  {
    id: 'set_reminder_1h',
    step: 'set_reminder_1h' as DoctorBookingStep,
    phase: 'calendar',
    label: '1h Reminder',
    description: 'Setting 1-hour reminder...',
    status: 'pending',
    icon: 'notifications-outline',
    color: '#8B5CF6',
    accentColor: '#A78BFA',
  },
  {
    id: 'schedule_followup',
    step: 'schedule_followup' as DoctorBookingStep,
    phase: 'calendar',
    label: 'Follow-up',
    description: 'Scheduling follow-up appointment...',
    status: 'pending',
    icon: 'calendar-number-outline',
    color: '#EC4899',
    accentColor: '#F472B6',
  },
  {
    id: 'setup_prescription_delivery',
    step: 'setup_prescription_delivery' as DoctorBookingStep,
    phase: 'confirm',
    label: 'Rx Delivery',
    description: 'Setting up prescription delivery...',
    status: 'pending',
    icon: 'cube-outline',
    color: '#10B981',
    accentColor: '#34D399',
  },
  {
    id: 'enable_records_sharing',
    step: 'enable_records_sharing' as DoctorBookingStep,
    phase: 'confirm',
    label: 'Records Sharing',
    description: 'Enabling medical records sharing...',
    status: 'pending',
    icon: 'share-outline',
    color: '#06B6D4',
    accentColor: '#22D3EE',
  },
];

// ============================================
// HELPER FUNCTIONS
// ============================================

export type BookingType = 'flight' | 'ride' | 'doctor';

/**
 * Get all granular steps for a specific booking type
 */
export function getAllStepsForBookingType(bookingType: BookingType): StepMetadata[] {
  switch (bookingType) {
    case 'flight':
      return [
        ...FLIGHT_PLANNING_STEPS,
        ...FLIGHT_SEARCH_STEPS,
        ...FLIGHT_COMPARE_STEPS,
        ...FLIGHT_BOOKING_STEPS,
      ];
    case 'ride':
      return [
        ...RIDE_PLANNING_STEPS,
        ...RIDE_SEARCH_STEPS,
        ...RIDE_BOOKING_STEPS,
      ];
    case 'doctor':
      return [
        ...DOCTOR_PLANNING_STEPS,
        ...DOCTOR_SEARCH_STEPS,
        ...DOCTOR_COMPARE_STEPS,
        ...DOCTOR_BOOKING_STEPS,
      ];
    default:
      return FLIGHT_PLANNING_STEPS;
  }
}

/**
 * Get steps for a specific phase
 */
export function getStepsForPhase(
  bookingType: BookingType,
  phase: 'planning' | 'searching' | 'comparing' | 'booking'
): StepMetadata[] {
  switch (bookingType) {
    case 'flight':
      if (phase === 'planning') return FLIGHT_PLANNING_STEPS;
      if (phase === 'searching') return FLIGHT_SEARCH_STEPS;
      if (phase === 'comparing') return FLIGHT_COMPARE_STEPS;
      if (phase === 'booking') return FLIGHT_BOOKING_STEPS;
      break;
    case 'ride':
      if (phase === 'planning') return RIDE_PLANNING_STEPS;
      if (phase === 'searching') return RIDE_SEARCH_STEPS;
      if (phase === 'booking') return RIDE_BOOKING_STEPS;
      break;
    case 'doctor':
      if (phase === 'planning') return DOCTOR_PLANNING_STEPS;
      if (phase === 'searching') return DOCTOR_SEARCH_STEPS;
      if (phase === 'comparing') return DOCTOR_COMPARE_STEPS;
      if (phase === 'booking') return DOCTOR_BOOKING_STEPS;
      break;
  }
  return [];
}

/**
 * Create a deep copy of steps with fresh status
 */
export function initializeSteps(steps: StepMetadata[]): StepMetadata[] {
  return steps.map(step => ({
    ...step,
    status: 'pending' as const,
    startTime: undefined,
    endTime: undefined,
    duration: undefined,
    progress: 0,
    details: undefined,
    error: undefined,
  }));
}

/**
 * Update a specific step's status and details
 */
export function updateStepStatus(
  steps: StepMetadata[],
  stepId: string,
  status: StepStatus,
  details?: StepMetadata['details'],
  progress?: number
): StepMetadata[] {
  return steps.map(step => {
    if (step.id === stepId) {
      const now = Date.now();
      return {
        ...step,
        status,
        details: details || step.details,
        progress: progress !== undefined ? progress : (status === 'completed' ? 100 : step.progress),
        startTime: status === 'active' && !step.startTime ? now : step.startTime,
        endTime: status === 'completed' || status === 'failed' ? now : step.endTime,
        duration: status === 'completed' || status === 'failed'
          ? (step.startTime ? now - step.startTime : 0)
          : step.duration,
      };
    }
    return step;
  });
}

/**
 * Get overall progress percentage
 */
export function calculateOverallProgress(steps: StepMetadata[]): number {
  if (steps.length === 0) return 0;

  const totalProgress = steps.reduce((sum, step) => {
    if (step.status === 'completed') return sum + 100;
    if (step.status === 'active') return sum + (step.progress || 50);
    return sum;
  }, 0);

  return Math.round(totalProgress / steps.length);
}

/**
 * Get current active step
 */
export function getCurrentStep(steps: StepMetadata[]): StepMetadata | null {
  return steps.find(step => step.status === 'active') || null;
}

/**
 * Get next pending step
 */
export function getNextPendingStep(steps: StepMetadata[]): StepMetadata | null {
  return steps.find(step => step.status === 'pending') || null;
}

